.credentials.json: ENC[AES256_GCM,data:eWI1zf9oII6Fnh2Iwc7Ktc1nZ2w+lyRummA3z+afoGTnBhPpR4E2/C0lwn2NW2sai9af+IxuRpKTOQBnDucR0BMpg7nbB9ruRCl42LpI50x/BgqNkODqpPUmHs5rYYO7nt0N+GdJBi76CBE4tW+iBHSgqYlIjlfs/eiWOF2OhnKzsYRTzDLWS33KcaaPJ+cE3sIEho7JBSQL2vpKvtKkTJW9LN8hytjS0hY02ST3mH6XVERZYwEILWwHE4Gj5rbMD0US9DfoRBjwluxz+AuZvXrc/67Lauuc/0HAJT5CzXJoWhrXZoa+RxLIyy/Xo8N8KL8WqA2QmICyJmQf5ic5GpRvNQTAb0Ug/HFeXfkV8WHsFnBfmSb2rWHLWpt8iyGcdyyHJJDrhI0u8FNy/aeL/3X7LDZWpF8nhhCqWS5i95IMC35EvxcFuj2bGJTEJnPUXs/O7sfd6NkG75IxxAG1YUJxMJ3Zmd0l96AqnGIWaqd25XBQTB4skF9cbXkyxa7B7UXPxR4bwCbzktjk6swN3MBwCF8bngYteMI5LO0C5AREe2+DFQj3WndDTiP08Kgm9bTO08iZjRHVwizpovWd+fkFIY/UbkH+dU2SJGQSAi373Q8=,iv:7+pDsbo6FePI+fopok2a0+nYZUoBihZrZ5u/FaD6HXw=,tag:ha//0i3k5zD9BGcK/DnfMg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5UUJ0SWQ3SHY1UXdwL3V5
            YmtKdUpwdGJzanczczNPNlhIdks4R1A5NXpJClN2LzNHWENHL0hsS1dFY0YrR1lY
            dDVINGVZVjRsWEhFTDdMU2ZhS2ZNUlkKLS0tIEtCRWVaN1doazV3cDNpcUR4SmUy
            RFpacVNEdnl5b0xXRDZpaFJrTE9PaUEKc3/IMvaYX/sx14n7bVkB0o19HfqKS5NC
            uBRB0bv+Aqom0ba7vCNqBS4d13elO4gXWAM+uT/q17Xm+Dk7EZl10g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age14zj8xa84qtky4rs0xkcvyfg5gf3004rw2lls8wpxjceqlda9vc9qjyza4y
    lastmodified: "2026-07-05T04:08:23Z"
    mac: ENC[AES256_GCM,data:pSRcHg1+5Hjl+TYiw/ZnmY6TLicIFYEFIETN4CzFPiAxDXj0m2aQCYL+ex96XHWImNm02i04X8n8RlBCDdRzYRjxFw3I2grtVxc8EvxhypW8T03lUkmLsvLHnnoM6TuUf1lLfe3u69j5bai+mpcQGsVxNn/9VWuZetunh6PxTEM=,iv:KViixONk0YMiv6PxOkCvtTYF+LC1g8BRo4nly+d0j3w=,tag:qU92fMdKI21O8I7AoGSSuA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
