{
	"data": "ENC[AES256_GCM,data:GVfMWNb+5YPCzy8xWeVkgF6k9gljyRsoi0FJB+Kll1zh1/7i3oe48sXZWfVKjNOsLGWGokQB4diAMRSiAyQvD4qFLrDIQ5n+Kb+QCgRBfymQ4bdr+DmSVMp6cYnPacERN3RKK4bk/Hc6lqy+Zd+ROX0Ad5gUOO2MoQxqF5EFDLQ48vMWFlLB/WwJZvkfjOonOpoxfV+CgB7V1iLV6DIdD5LpiB4+c11jyCg/mNH5J8kZdSb5oTF1V7Sb761ZP2i9xwlMBrcb9Klw7EM0fc1mjFk8+jM=,iv:H2W9xF1+JIYuZ+8LEp0W7XbeElu1f5CNpoLrTrVNb5k=,tag:rY3FQBnZLIU7NJ/vWE4JvA==,type:str]",
	"sops": {
		"age": [
			{
				"enc": "-----BEGIN AGE ENCRYPTED FILE-----\nYWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDZzBYbnFDMURBdkxLNld5\naURGcVNvWlBBdEdRMEszRFY3UWZQeVQ1a1JJCnN6dTZ5TTlFekNtR0FhaDczS2tQ\nWHhidkFhdzlNUUlQOUZnYVBwblJJNGcKLS0tIElON0I3V2xmdmFnNUcwdUJZTytn\nYTVaOW5PZFFZQWdEcktmNktub3hnRkEKXJLIrbDqCoGCJ5o9RUWxhS+0Wtl7cji7\nNUlOuUmDgmkzS591W8tsGtEhNdoPWTxFWD68T1ZE2xSemR0ML6/f9Q==\n-----END AGE ENCRYPTED FILE-----\n",
				"recipient": "age14zj8xa84qtky4rs0xkcvyfg5gf3004rw2lls8wpxjceqlda9vc9qjyza4y"
			}
		],
		"lastmodified": "2026-07-13T12:59:49Z",
		"mac": "ENC[AES256_GCM,data:vlNwG/a6MOU7Z9curgoH9rpUg/saifbFjFEn031mH1OsDTReFX2sb0kNJf7yhDkWLO18pT0jCE7hwN6QOh6KFMBezwPfeH9nIN+i5z5p1yYdk+9AUSRP9cvtBkelDLE2R1R+V8n8CiHifOt9yv349WliG7tc+6OE8YfjqDiE7g0=,iv:T/HsIMXUBWe3vm+DhKhWe5xunTWUiIFbm28b8JjT+CM=,tag:krCMn6Toul80Ib9RMJRxHA==,type:str]",
		"version": "3.13.1"
	}
}
